### PR TITLE
Variable Testcases Shuting

### PR DESCRIPTION
**Pull request by Shuting-sli2**
10 testcases

### CODE REVIEW

**Comment by justinnhli** [comment]
1. `expressionWithVars.lang` has two non-ASCII characters (the open-paren on the last line, and the semicolon on the last line).
2. Both `undefinedVar` and `varAlreadyDefined` should be runtime errors, not syntax errors.
3. Can you put more spaces in your s-expressions? There should be a space before every open-paren. (I *could* write a parser to parse the s-expressions, but instead I'm just using regular expressions ;))

Comment and tag me when you're done!

**Comment by Shuting-sli2** [comment]
@justinnhli 
Thank you for the review. Just updated.
I added spaces before open parenthesis although I'm not sure what's the difference between regular expression and s-expression.

**Comment by justinnhli** [comment]
Regular expressions is a language to parse/match strings. It's easier to write than parsers, but not as powerful. See Wikipedia for more: https://en.wikipedia.org/wiki/Regular_expression

1. Both `undefinedVar` and `varAlreadyDefined` will need s-expressions (since they are no longer syntax errors.
2. `assignVarWithItself` `fibonacci` needs to be on the same line (since I replace newlines with spaces when I compare).
3. `expressionWithVars` has a typo (`lookuop` -> `lookup`). The parenthesis for the final `lookup` are also screwed up.
4. `mathExpressionAsVar` has an extra parenthesis in the `declare` (before the `/`).
5. Similarly, `modifyVariable` has some extra parentheses.
6. Ditto `switchVars`. The `assign` nodes will also need a `varloc`.

Let me know if these don't make sense, and tag me when you're done!

**Comment by Shuting-sli2** [comment]
@justinnhli

**Comment by justinnhli** [comment]
I had to fix a few of your s-expresssions, but this looks good otherwise!

**Pull request merged**
