### PR TITLE
Updated test cases

### PR DESCRIPTION
**Pull request by g-sarapata**

### CODE REVIEW

**Comment by justinnhli** [comment]
Okay, we'll have to do this in parts:

* Arithmetic 10.out is wrong
* Arithmetic 2.lang doesn't work - `print3;` is interpreted as a variable, so it's a syntactically valid lang program (albeit one that will immediately cause a variable undefined runtime error).
* Similarly, variables 5.lang is syntactically valid.
* Variables 6.lang, on the other hand, is *not* syntactically valid - lang does not allow for a variable declaration without an initial value.
* Loops 3.sexp, 4.sexp, 5.lang, 5.sexp, 7.sexp, and 9.sexp still has `true` and `false`
* Loops 5.out, 8.out, 10.sexp and 10.out all contain errors
* Functions 5.lang doesn't test for what your comment says it tests for
* Functions 10.lang has a spelling error

Let's start with these; tag me when you're done, and we can look at classes, transforms, and types.

**Comment by g-sarapata** [comment]
Okay I think I fixed the errors you mentioned.

**Comment by justinnhli** [comment]
Not quite:

* Variables 5.lang is still an undefined variable, not a syntax error
* Loops 3, 4, 5, 7, 9 all have S-expression issues - you don't need to `lookup` an integer.
* Functions 10.sexp needs to be updated for the spelling error

**Comment by g-sarapata** [comment]
I have updated those files

**Comment by justinnhli** [comment]
Great. Glancing through the remaining tests:

* You don't have any transforms test cases yet (all the files are empty)
* Your class test cases have a consistent problem of 1. leaving out the object as the first argument to member functions, and 2. not printing anything
* Your typechecking cases are... fine? I'll accept them, they're just boring since they never cause a type mismatch

**Comment by g-sarapata** [comment]
I have tried to updates transforms and classes but I'm not quite sure what you mean when you say leaving the object out as the first argument to member functions.

**Comment by justinnhli** [comment]
if you have:

```
var Foo = class {
  var bar = func(n) {
    print n;
  };
};
Foo().bar();
```

This will print `obj`, because the object itself is always the first argument to a member function. Python does this as well, or you can look back at the lectures for a reminder.

**Comment by g-sarapata** [comment]
if I have:
var Foo = class {
  var bar = func(n) {
     print n * 2;
  };
};
Foo().bar();


would it print out obj * 2?

**Comment by justinnhli** [comment]
To repeat what I said on Slack: your `n*2` would result in a `math operation on functions` runtime error

**Comment by g-sarapata** [comment]
Okay I think I fixed it

**Comment by justinnhli** [comment]
* Transforms 3.sexp2, 6.sexp2, 6.out, 9.sexp2, 9.out are wrong
* Typechecking 10.out is wrong
* For your class tests, you can't just assume the first argument will be the object and change nothing else. Tests 1-6, 8-10 all now have incorrect output because of the error you've introduced by doing this.

**Comment by g-sarapata** [comment]
I changed transforms and types but I'm not sure what you mean with classes

**Comment by justinnhli** [comment]
You wrote your outputs assuming that the arguments would be what you pass in, forgetting that the object itself would be the first argument. This means that the outputs are all wrong.

**Comment by g-sarapata** [comment]
Is this what you mean?

**Comment by justinnhli** [comment]
Good! Almost there:

* The math on transforms test 6 is wrong - you'll need to change both the `.sexp2` file and the `.out` file.
* I don't quite know what you want for classes test 7 - for one, you have both `test` and `Test`, and you didn't instantiate the class. Please check all three files to make sure they match what you want to test.

**Comment by g-sarapata** [comment]
Fixed it

**Comment by justinnhli** [comment]
Fix classes test 10 (likely all three files) and you should be good!

**Comment by g-sarapata** [comment]
Fixed classes test 10

**Comment by justinnhli** [comment]
merged.

**Pull request closed without merging**
