### PR TITLE
Added transform test cases

### PR DESCRIPTION
**Pull request by jack-thomascolwell**
@justinnhli I have added the transform test cases

### CODE REVIEW

**Comment by justinnhli** [comment]
* 8.lang and 9.lang needs a space after `print`. The S-expressions also have the wrong associativity - you have `(+ 1 (+ 1 1))` instead of `(+ (+1 1) 1)`
* Ditto with 5.sexp
* 6.lang is missing a semicolon
* 10.sexp2 needs a `lookup`.
* 10.out should be `undefined variable` :)

**Comment by jack-thomascolwell** [comment]
@justinnhli I think I have fixed all of the issues

**Comment by justinnhli** [comment]
* 5.sexp and 5.sexp2 still has the same associativity problem.
* 10.out has a space at the end which was hard to track down. I'll update the code next time to get rid of that, but please change it for now :)

**Comment by jack-thomascolwell** [comment]
@justinnhli I have fixed those test cases

**Comment by justinnhli** [comment]
Merged!

**Pull request merged**
