### PR TITLE
function test cases

### PR DESCRIPTION
**Pull request by bryceboyle**

### CODE REVIEW

**Comment by justinnhli** [comment]
* 1.sexp should have `varloc` in place of `lookup` for the assign statement.
* 5.lang is missing a semicolon
* 6.sexp has two `(function)`'s. You'll need to rebalance the parentheses.
* 7.sexp is not a syntax error because that's allowed for the typed version of lang
* 10.lang is not an error at all - the extra return never executes

**Comment by bryceboyle** [comment]
@justinnhli I think they should be fixed now

**Comment by justinnhli** [comment]
I didn't run them, but I think you'll need to update 10.sexp as well for the print.

**Comment by bryceboyle** [comment]
shoot sorry, I just added that. I also didn't mean to commit that older loops test case

**Comment by justinnhli** [comment]
* 10.sexp has an incorrect parenthesis around `(lookup sum)`
* 2.sexp is missing a `(print ... )`

Fix those and you should be good!

**Comment by justinnhli** [comment]
Merged. Thanks!

**Pull request merged**
