### PR TITLE
classes, typing, transforms

### PR DESCRIPTION
**Pull request by SophieStankus**
@justinnhli 
1. sorry for the dump of 30 tests at once
2. I realized I def didn't ever do reverse(?) pull requests so my file numbering (e.g. typing and transform file #s got changed I think) is a bit off for these let me know if I should fix that somehow

### CODE REVIEW

**Comment by justinnhli** [comment]
Don't worry about the numbering - I'll fix them when I merge.

* Transforms 2, 3, 8, 9 have errors in the S-expression - they should be left associative (+ (+ 1 1) 1) instead of right associative (+ 1 (+ 1 1))
* Transforms 7.out is wrong, should be 10
* Transforms 10.lang should end with `x()`, not `func()`
* Classes 6 and 8 should not have a `(class (sequence (declare ...` - the `sequence` should not be there.
* Classes 1.lang needs to "call"/instantiate the class first with `x().y`. The S-expression needs to change accordingly.
* Classes 4.sexp should have a final `y` instead of an `a`
* Classes 5 and 6 are not syntax errors - they would be runtime errors if you actually instantiate the classes.
* Typechecking 6.sexp is missing a `(call ... (arguments))`.

**Comment by SophieStankus** [comment]
@justinnhli ready for a second pass - classes 5 was already a runtime error so I didn't change that I'm not sure if you meant a different test case. and type checking 6 I just deleted the first instantiation

**Comment by justinnhli** [comment]
* Transforms 3.sexp is missing a close paren
* Transforms 8.sexp, 9.sexp, and 9.sexp all have the same associativity problem - you have something like `(+ 1 (+ 2 3))`, when it should be `(+ (+ 1 2) 3)`
* Classes 1.sexp has call and member in the wrong order. You're also missing a `(arguments)` for the call.
* Classes 3, 5, and 6 are both *not* syntax errors, nor runtime errors, which is why you need the sexp files.

**Comment by SophieStankus** [comment]
@justinnhli ok ready for another review but a couple qs - 1. I'm not sure where to add a paren in transforms 3.sexp, like I think it does have the right amount? 2. Transforms 9.sexp doesn't have any associativity in the format you mentioned so I'm also a bit confused on what to change there

**Comment by SophieStankus** [comment]
@justinnhli ok tried again - still not 100% sure about the transform 8.sexp but other than that

**Comment by SophieStankus** [comment]
@justinnhli added classes 3.sexp & nine.sexp2

**Comment by justinnhli** [comment]
merged!

**Pull request merged**
