### PR TITLE
class cases 

### PR DESCRIPTION
**Pull request by dylane1999**
class test cases @justinnhli

### CODE REVIEW

**Comment by justinnhli** [comment]
Good. There's just one error in the classes test cases:

* test_1.out is wrong - I'm not sure what you're trying to here, but the `print` never runs (nor are there errors).

A few errors in the transform test cases:

* test_1.lang has the output accidentally pasted in
* test_6.out is wrong
* test_6.sexp2 is wrong. Keep in mind that you want expand all add/sub terms first, before rearranging and re-encoding them.
* test_9.sexp2 ditto.

**Comment by dylane1999** [comment]
fixed I think @justinnhli

**Comment by justinnhli** [comment]
Close! Classes test 1 is still off. I think you meant `var x = foo();` instead of `x = foo();`. You'll also need to update the S-expression.

**Comment by dylane1999** [comment]
@justinnhli fixed test 1

**Comment by justinnhli** [comment]
merged! thanks

**Pull request merged**
