### PR TITLE
Loops Tests

### PR DESCRIPTION
**Pull request by Sachacode**
First attempt at loop test cases

### CODE REVIEW

**Comment by justinnhli** [comment]
* In multiple places in your S-expressions have you something like `(1)`. Integers by themselves should not be wrapped in parenthesis.
* In test2.sexp, test5.sexp, and test10.sexp all have S-expressions that do not match the program, either missing lines or different integer values
* test2.sexp also has issues with missing parenthesis around `print`
* test5.out has an incorrect output for the last line
* test7.lang has incorrect syntax - the brace should come after the condition
* test7.sexp is missing a `sequence`
* test9.sexp has parethenses in the wrong places (the statements are grouped incorrectly)

Fix them and tag me again!

**Comment by Sachacode** [comment]
@justinnhli fixed loop test cases

**Comment by justinnhli** [comment]
* Tests 1, 2, 3, and 10 still have incorrect S-expressions
* Tests 5 and 9 have incorrect output

**Comment by Sachacode** [comment]
@justinnhli loop tests ready for review

**Comment by justinnhli** [comment]
Almost - test2.sexp should have `(declare a 1)` instead of `(declare a 0)`, but otherwise you are good!

**Comment by Sachacode** [comment]
@justinnhli Fixed test2.sexp

**Comment by justinnhli** [comment]
Merged. Thanks!

**Pull request merged**
