### PR TITLE
Add ten control flow tests

### PR DESCRIPTION
**Pull request by kathyyliu**

### CODE REVIEW

**Comment by justinnhli** [comment]
@kathyyliu A few minor things:

1. Test 6 is missing a `ret inner` from `outer`. The s-expression will need to change according.
2. The s-expression for test 6 is also missing a `(function ...` for when you `(declare inner ...`
3. Tests 7 and 8 have a spelling error (`argumetns` instead of `arguments`).
4. Test 7 is missing a semicolon after `myfunc()`

Looks good otherwise!

**Comment by kathyyliu** [comment]
@justinnhli fixed!

**Comment by justinnhli** [comment]
Fixed a small typo for you, but merged. Thanks!

**Comment by kathyyliu** [comment]
oops, sorry about that!

**Pull request merged**
