### PR TITLE
Add variable test cases

### PR DESCRIPTION
**Pull request by mhultgren**

### CODE REVIEW

**Comment by justinnhli** [comment]
1. The s-expression for test 0 has an unnecessary parenthesis around `3`.
2. The s-expressions of tests 1, 2 should be wrapped in a `sequence`, since everything we're running will be a program (ie. a sequence of statements). 
3. It should also have an error as the expected output.

Okay, I see - you're treating each test case as though it's one line of a larger program, but they should have been self-contained programs. You'll need to combine them (and write more), or correct the s-expression and output for what will happen if they are run separately.

**Comment by mhultgren** [comment]
Variable test cases have been fixed, and loop test cases have been added.

**Comment by justinnhli** [comment]
1. Variables test 2 has an incorrect output.
2. Control Flow test 8 is incorrect - the output should be 3, not 300.

Can you comment and tag me when you've fixed these two issues?

**Comment by mhultgren** [comment]
Both should be fixed, @justinnhli

**Comment by justinnhli** [comment]
Looks good. Thanks!

**Pull request merged**
