### PR TITLE
Test Cases Shuting Li

### PR DESCRIPTION
**Pull request by Shuting-sli2**

### CODE REVIEW

**Comment by justinnhli** [comment]
Good test cases! I like what you're trying to do, even if they didn't work out:

1. The output files should not contain semicolons - it should be just the value of what is printed.

2. `character.lang` and `endSign.lang` both require parsing only *parts* of the file, not the whole file. (A similar test case is how I realized I needed to clarify this to the class).

3. `commentAsSpace.lang` doesn't work - the semicolon will be considered part of the comment. You can try instead:

    ```
    print 1+1#hello
    ;
    ```

4. `newlineAsSpace.lang` has a different issue - the `\n` is treated as a literal backslash `\`, followed by the letter n `n`. What you want to test is:

    ```
    print 1+1
    ;
    ```

Still, I really like these test cases, since it shows you're thinking through what is allowed by the grammar. Tweak them and tag me again!

**Comment by Shuting-sli2** [comment]
Hi Justin, thanks for your feedback. Appreciate it. I just made some changes based on your advice. I don't know if you can see  my second commit in this pull request or do I need to create a new pull request?

**Comment by justinnhli** [comment]
Haven't looked at it yet, but just the same PR is fine!

**Comment by justinnhli** [comment]
Accepted. Thanks!

**Pull request merged**
