### PR TITLE
Add 10 types cases

### PR DESCRIPTION
**Pull request by kathyyliu**

### CODE REVIEW

**Comment by justinnhli** [comment]
Close!

* 3.sexp shouldn't have a `var` in the declare - the myfunc variable is untyped (which is different from the *function* being typed)
* 7.sexp misspelled signature
* 9.out should also have `type mismatch` - your function doesn't return anything when it should
* 10.out should *not* have `type mismatch` - since there's no return type, it defaults to `var`, which matches the default return value of `0`

**Comment by kathyyliu** [comment]
@justinnhli Should be good now

**Comment by justinnhli** [comment]
Close - nine.out only errors when the function returns, so the body still executes (ie. it still prints)

**Comment by kathyyliu** [comment]
@justinnhli Thanks for the catch!

**Comment by justinnhli** [comment]
Merged!

**Pull request merged**
