### PR TITLE
Math expression test cases

### PR DESCRIPTION
**Pull request by jack-thomascolwell**

### CODE REVIEW

**Comment by jack-thomascolwell** [comment]
@justinnhli

**Comment by justinnhli** [comment]
What's happening with `eight.lang`? You might have mixed up the input and the output. Also note that your program does *not* only contain expressions, since you are still printing stuff.

**Comment by jack-thomascolwell** [comment]
@justinnhli I have fixed the issue with test case eight from the arithmetic expressions. The variable test cases have also been added but GitHub won't let me make a second pull request for those.

**Comment by justinnhli** [comment]
Your math test cases are fine. The variable ones need a few changes:

1. Tests 2, 5, 6 all lead to syntax errors. Lang does not allow declaring variable without an initial value.
2. You have a typo in the s-expression for test 7 - the 3 should be a 2.

You're good otherwise!

**Comment by jack-thomascolwell** [comment]
@justinnhli I have added the control flow test cases and will commit with the updated variable test cases shortly

**Comment by justinnhli** [comment]
Great.

1. Test 2 is missing the last assignment in the s-expression.
2. Test 3 has a typo in the s-expression - the last comparison is the wrong way around.
3. Test 10 is currently an infinite loop. Your s-expression suggests that the condition of the while should be a `0`.

Fix these two and the variable test cases and tag me again!

**Comment by jack-thomascolwell** [comment]
@justinnhli I have fixed the variable and control flow test cases.

**Comment by justinnhli** [comment]
LGTM. Thanks!

**Pull request merged**
