### PR TITLE
Function Tests

### PR DESCRIPTION
**Pull request by Sachacode**
@justinnhli Here are my function test cases.

### CODE REVIEW

**Comment by justinnhli** [comment]
__Functions__

* test1.lang has a misnamed function
* test2.lang should not be typed
* test2.sexp is missing a `lookup` and the final assignment
* test4.sexp has a `ret` that should be `return`
* test6.sexp has an incorrect number
* test7.sexp is missing an initial declare, and the final function call is wrong
* test8.sexp has an extra `=`, and a close-paren is in the wrong place
* test9.sexp has one too many `+`. The parens are also wrong, as is the final function call.

__Transforms__

You need two S-expression files here - a `.sexp` with the original S-expression, and a `.sexp2` with the transformed S-expression.

__Classes__

You have a consistent error where your `(declare c ...` is missing a `(call`, as well as spelling error for `(argument)`. You also have an extra S-expression for `c.b = 10` in multi

* test1.lang is wrong, since you need to create an instance of A first. The S-expression will need to change as a result.
* test4.lang, test5.lang, and test7.lang are all missing a semicolon

There are others, but fix them first and I'll take another look.

**Comment by Sachacode** [comment]
@justinnhli I fixed the test cases and I added the type cases as well.

**Comment by justinnhli** [comment]
Transforms:

* 1.sexp is missing a paren; 1.sexp2 shouldn't have negative numbers.
* 2.lang and 4.lang are both missing semi-colons.
* 4.sexp2 and 4.out are both wrong - check your math.
* 5.sexp2 is wrong - there should almost never be `0` in the transformed S-expression, unless it's at the start of an all-negative expression.
* 6.sexp and 6.sexp2 are both wrong given your code
* 9.sexp and 9.sexp2 should both have `declare` instead of `var`

Classes:

* 1.sexp has spelling errors, `lookup` instead of `varloc`, and a mistake for the final call
* 2.lang needs a `this` argument for the member function. 2.sexp needs to be changed for that, and you also need to fix the capitalization
* 5.sexp has an extra line
* 7.sexp is missing `(parameters)`, and should be using `return` instead of `ret`
* 7.out is wrong
* 8.sexp has an extra line.

Tag me again when you're ready.

**Comment by Sachacode** [comment]
@justinnhli I fixed transform and class cases

**Comment by justinnhli** [comment]
* Transforms 6.sexp2 can be further simplified
* Transforms 9.sexp is missing a close paren
* Classes 1.sexp has multiple issues - please double check to make sure it matches the lang code
* Classes 2.sexp is missing the final `(arguments)`
* Classes 7.sexp still has `ret` instead of `return`
* Classes 7.out is wrong - you are returning the class, so `static` is never printed

**Comment by Sachacode** [comment]
@justinnhli I fixed the previous files.

**Comment by justinnhli** [comment]
* Classes 7.sexp has a bunch issues, including but not limited to spelling errors
* Your typecking sexps have consistent issues, including missing `lookup` and not matching your code. I recommend going back and double checking your s-expression line by line with your code.

**Comment by Sachacode** [comment]
@justinnhli FIxed class and type tests

**Comment by justinnhli** [comment]
Much better!

* Classes 1.sexp has multiple issues, including multiple spelling errors and multiple expression that don't match the code.
* Typechecking 4.sexp has the last two variables wrong
* Typechecking 4.out should be `2` - I'm not sure where you thought there will be a type mismatch
* Typechecking 8.sexp shouldn't have a type for `a`, and has the wrong type for `b`
* Typechecking 9.lang has a negative number, which is not allowed in lang. Represent it as `(0 - 1)`. You'll need to change the S-expression as well.

**Comment by Sachacode** [comment]
@justinnhli made the fixes.

**Comment by justinnhli** [comment]
* Classes 1.sexp is wrong where you call the constructor
* Typechecking 9.sexp should have `i` instead of `n`, you need `(lookup i)` when used as arguments, and you have an extra set of paranthesis around one of the `(call ...)`s

**Comment by Sachacode** [comment]
@justinnhli I think I got the last fixes.

**Comment by justinnhli** [comment]
Finally merged!

**Pull request merged**
