### PR TITLE
Class_Shuting

### PR DESCRIPTION
**Pull request by Shuting-sli2**
@justinnhli

### CODE REVIEW

**Comment by Shuting-sli2** [comment]
@justinnhli transform test cases added

**Comment by Shuting-sli2** [comment]
@justinnhli type test cases added. Thank you.

**Comment by justinnhli** [comment]
* Transforms 3.sexp2 is wrong - you should further simplify the constants
* Classes 2.lang is missing an argument when you call `f`
* Classes 6.lang doesn't work - `c_val` will have the value of the integer, and won't be a *pointer* to the integer, and so your code right now goes into an infinite loop.
* Classes 7.lang has an error in `ret n = n / 2`. You'll need to change the S-expression as well
* Classes 9.lang is missing an argument for the member function - remember that the object is passed in automatically. You'll need to change the S-expression as well/
* Typechecking 3.lang is calling `outter` one too many times, if you want to cause a type mismatch. It currently *does* work because the empty function returns `0` implicitly.
* Same for Typechecking 4.lang - `num` will be an integer based on your current code.
* Typechecking 5.lang, `a` to `e` are all *functions*, not *integers*. You'll need to change the function signature as well.
* Typechecking 6.lang `mytype()` is an object, not an integer.
* Typechecking 9.lang, I think you want to rename `foo` to `b`, and remove the final declaration
* Typechecking 10.sexp has the wrong type in the signature for `f`

**Comment by Shuting-sli2** [comment]
@justinnhli Updated class, transform, and type. Thank you!

**Comment by justinnhli** [comment]
Not quite:

* Typechecking 3 still needs work - right now your `num` will be a function. You're also not printing anything, so your output file is wrong. Remember to update your S-expression as well!
* Typechecking 4.sexp has the wrong function signature
* Typechecking 5.sexp has the same wrong function signature. You also need to add the signature to returned anonymous function
* Typechecking 10.sexp has the wrong function signature

**Comment by Shuting-sli2** [comment]
@justinnhli updated type-checking. Thank you.

**Comment by justinnhli** [comment]
Both the signature for F, and for the returned function, are wrong for 5.sexp. Check the type of the return value!

**Comment by Shuting-sli2** [comment]
[image: image.png]

I thought the type of return value for both F and the returned function are
supposed to be 'func'?

**Comment by justinnhli** [comment]
Oops, sorry, not F, for `addition`.

For the returned function, your lang file doesn't have a type for the return (but your sexp does)

**Comment by Shuting-sli2** [comment]
For type checking 5.sexp,  I still thought the return type of addition function was 'func'?

**Comment by justinnhli** [comment]
merged!

**Pull request merged**
