### PR TITLE
add typing test cases

### PR DESCRIPTION
**Pull request by bryceboyle**

### CODE REVIEW

**Comment by justinnhli** [comment]
* 1.sexp should have `declare` instead of `define`, and you're missing parenthesis around the `return`
* 3.sexp is returning the wrong value
* 4.out is wrong
* 5.sexp declares `computer` as a `func` type, but that's not in 5.lang. Your values for `i` and `j` are also swapped.
* 8.sexp is missing the final `(arguments)`
* 10.sexp misspelled `lookup`

**Comment by justinnhli** [comment]
merged!

**Comment by bryceboyle** [comment]
@justinnhli SOrry just to make sure,  is that including the transforms test cases?

**Comment by justinnhli** [comment]
lol yep. I spotted them ten minutes later. I just fixed them for you

**Comment by bryceboyle** [comment]
ah okay thank you!

**Pull request merged**
