### PR TITLE
Added function test cases

### PR DESCRIPTION
**Pull request by jack-thomascolwell**
@justinnhli I have added the function test cases.

### CODE REVIEW

**Comment by justinnhli** [comment]
Nice set of tests.

* The keywords in `lang` are `func` and `ret`, not `function` and `return`. The way to remember it is that `lang` only uses the first syllable :)
* Function declarations are declaration statements, which means that there should be a semicolon after the closing brace.
* Similar, if a line only has an expression (eg. `x+1`), it is also a statement, and should end with a semicolon.
* Test 6 has two issues. First, `lang` doesn't have negative numeric literals, so you can't write `print -12;`. Either change the number, or write `print 0-12;`. Second, the S-expression for Boolean negation is `(! ...)`, not `(not ...)`.

Everything looks good otherwise!

**Comment by jack-thomascolwell** [comment]
@justinnhli I have updated the test cases.

**Comment by justinnhli** [comment]
Close!

* Test 7 has an extraneous semicolon after the if statement
* Test 9 has `return` instead of `ret`.

**Comment by jack-thomascolwell** [comment]
@justinnhli I have fixed tests 7 and 9.

**Comment by justinnhli** [comment]
LGTM. Thanks!

**Pull request merged**
