### PR TITLE
Title

### PR DESCRIPTION
**Pull request by SophieStankus**
function test cases @justinnhli

### CODE REVIEW

**Comment by justinnhli** [comment]
The variable test cases are good.

The control flow test cases have one small issue - test 7 is an infinite loop, which we cannot test for. You'll need to change that test.

The function test cases have several issues. First, all function definition/declarations are statements, and so need a semicolon at the end (like any other variable declarations). Second, the S-expression for a function call only takes one set of arguments, so your S-expression for (for example) test 8 is wrong. Take a look at my discussion with @dylane1999 on Slack from 2/27 for more details.

PS. I didn't look at all your test cases in depth, but your functions test 8 is also missing a return in the outer function.

**Comment by SophieStankus** [comment]
@justinnhli ok revised! sorry forgot this existed for a minute

**Comment by justinnhli** [comment]
Close!

* Loops test 7.sexp is missing a close paren at the end
* Functions 2.sexp and 3.sexp are both missing the final `(arguments ...)`
* Functions 4.sexp is printing the wrong thing inside a()
* Functions 5.lang should have `ret` instead of `return` :)
* Functions 8.lang is... wrong? I think you meant to `ret b;` instead of `b();`. Your 8.sexp is also wrong - the inner function should be inside the `(sequence ... )` of the outer function.
* Ditto functions 10.sexp

**Comment by SophieStankus** [comment]
@justinnhli revised :)

**Comment by justinnhli** [comment]
Merged. Thanks!

**Pull request merged**
