### PR TITLE
Spaces

### PR DESCRIPTION
**Pull request by Sachacode**
I don't know if the format is right but I have the first ten test cases.

### CODE REVIEW

**Comment by justinnhli** [comment]
Several issues:

* Test case 8's output should be `syntax error`, not `error`.
* Test case 7's output should be `runtime error: division by zero`, not `divide by 0 error`. Please double-check the error document on Moodle in the future for what the error printout should be.
* The rest test have two issues:
    1. You are missing the final semicolon for many (all?) of your programs.
    2. Your output should *not* have additional "comments". The output file should just be the printed output. First, this first batch of test cases will not be testing the internal representation at all. Second, when you add them for the next set of test cases, they should be in another `.sexp` file. (Note that your s-expressions should also have spacing, which they do not right now.)

**Comment by Sachacode** [comment]
@justinnhli  I think my variable test cases are lumped into this pull request I don't know how to separate it but if I need to do that I will ask about it.

**Comment by justinnhli** [comment]
You still need to fix the old tests - please do that before submitting any further tests.

**Comment by Sachacode** [comment]
@justinnhli I fixed my space test cases and they are ready for another look.

**Comment by justinnhli** [comment]
I realize I had a typo in my last comment, so apologies for making you fix the same test twice.

* Spaces/Math test 7 should be `runtime error: divide by zero`
* Spaces/Math test 9 assumes that number representations will overflow, which they won't. In general, I recommend staying away from testcases that use large numbers.

Your variable test cases have lots of issues, starting with syntax. I'm not sure where you got `int var num = 0;` or `string var str = "string";` from, but neither of those are valid lang. Your also put comments in your `.sexp` files, when they should be actual comments in your `.lang` file instead. For the S-expressions, please take a look at what other students have submitted and follow that format.

**Comment by justinnhli** [comment]
The math tests are good. Let me know when you've fixed/rewritten the variable tests.

**Comment by Sachacode** [comment]
@justinnhli I edited my variable cases.

**Comment by justinnhli** [comment]
Much better. For your variable tests:

* Test 1 is missing a semicolon in line 2. Your S-expression also has "varlock" instead of "varloc"
* Test 4 S-expression is missing a closing paren on line 3
* Test 5 S-expressions should have `declare`, and the last line should be a multiply instead of an add
* Test 8 S-expression is missing the print.

Fix those and I'll merge this PR!

**Comment by justinnhli** [comment]
LGTM. Thanks!

**Pull request merged**
