### PR TITLE
variable test cases

### PR DESCRIPTION
**Pull request by bryceboyle**

### CODE REVIEW

**Comment by justinnhli** [comment]
1. The s-expression for tests 2, 5, 7, 9 should have a `lookup` inside the `print`.
2. Tests 3 and 10 are runtime errors (since the syntax is correct), and so should have a s-expression.
3. The first line for test 4 is fine, but the *second* line is a syntax error (since `var` cannot be an identifier/expression). I think you meant to write `print else_1`.
4. Test 6 is a syntax error (since strings don't exist).
5. Test 7 also has a slightly wrong s-expression; the order of the expression is wrong.

**Comment by bryceboyle** [comment]
@justinnhli I've added my loops test cases but haven't fixed my variable test cases yet

**Comment by bryceboyle** [comment]
I (think) I have fixed my variables test cases

**Comment by justinnhli** [comment]
Fixed a few small s-expression things for you, but this looks good!

**Comment by justinnhli** [comment]
@bryceboyle There were more fixes that I somehow didn't catch the first time. Two consistent errors:

1. You're ending the branches and loops in the wrong place - the closing parentheses often got shifted to the end of the program, when they shouldn't be.
2. The Boolean comparison operators (`||`, etc.) still require looking up the variables, so it should be `(|| (lookup x) (lookup y))`, not `(|| x y)`

**Pull request merged**
