### PR TITLE
final test cases (loops through typechecking)

### PR DESCRIPTION
**Pull request by DanScal**
Here are all of the test cases that I have left to submit.

### CODE REVIEW

**Comment by justinnhli** [comment]
Classes:

* 1.sexp has a spelling error.
* 4.out is wrong.
* 5.lang, 7.lang both results in "member of non-object" error - you are trying to access a member of the *class*, when it should be of an *instance*.
* 8.lang is missing a semicolon.

Transforms:

* 1.sexp, 1.sexp2, 7.sexp2 are missing parentheses
* 2.sexp2, 9.sexp2 should have constants rearranged to be at the end
* 4.sexp2, 5.sexp2 is not fully simplified
* 8.sexp2 is missing a `lookup`

Typechecking:

* 4.sexp, 5.sexp have incorrect types for the arguments/return value
* 8.out has a spelling error
* 9.sexp is missing parentheses

**Comment by DanScal** [comment]
@justinnhli I believe I fixed the issues

**Comment by justinnhli** [comment]
* Classes 4.lang has the same class/instance issue
* Transforms 4.sexp2 can be further simplified
* Transforms 7.sexp2 and 9.sexp2 both have parenthesis issues

**Comment by DanScal** [comment]
@justinnhli round two

**Comment by justinnhli** [comment]
Transforms 7.sexp2 is still wrong - I encourage you to work through the transform by hand before re-encoding it as an S-expression.

**Comment by DanScal** [comment]
@justinnhli I'm a little confused on this one. The way I'm thinking about it, the only possible transformations are moving the constants to the back. Am I missing something here?

**Comment by justinnhli** [comment]
That's the only transformation, but as you re-encode it, the nesting of the S-expressions will shift.

**Comment by DanScal** [comment]
@justinnhli Okay NOW I think I got it

**Comment by justinnhli** [comment]
Check your parentheses :)

**Comment by DanScal** [comment]
@justinnhli how about now?

**Comment by justinnhli** [comment]
Not merging it into main (so to preserve what other students are testing against), but this is complete!

**Pull request closed without merging**
