### PR TITLE
Added class test cases

### PR DESCRIPTION
**Pull request by jack-thomascolwell**
@justinnhli I have added the test cases for classes

### CODE REVIEW

**Comment by justinnhli** [comment]
* 4.sexp is wrong - the last few nodes should be `(member (lookup Inst) a)`
* 7.lang probably should have `x.a` instead of `test.a`. The S-expression will also need to change.
* 8.sexp is missing `(argument)` for the `(call ... )`
* 9.lang is missing a bunch of semicolons.

**Comment by jack-thomascolwell** [comment]
@justinnhli I have fixed the classes testcases and added the typechecking test cases

**Comment by justinnhli** [comment]
* Classes 4.sexp is still wrong - the print should be `12`, not `1`, and the last `memloc` should be `member`
* Typing 8.out and 9.out should both say `type mismatch` instead of `argument mismatch` for the return type
* You misunderstood me when I said "all parameters must be typed" - this applies to the S-expression, not the syntax. So 6.lang would run and print `closure`.

**Comment by jack-thomascolwell** [comment]
@justinnhli I have fixed these test cases

**Comment by justinnhli** [comment]
Merged. Note that I fixed your classes test 4 - you had `1` instead of `12`.

**Pull request merged**
