### PR TITLE
Added variable test case files

### PR DESCRIPTION
**Pull request by SophieStankus**
@justinnhli

### CODE REVIEW

**Comment by justinnhli** [comment]
1. Test 3 and 4 are both missing a close paren in the sexp.
2. Test 5's print statement should be part of the sexp.
3. Test 7's bad variable name is a parsing error, not an illegal value (which we haven't gotten to yet)
4. Test 8: printing an undefined variable should be an undefined variable error, not an illegal value error. This means that there would still be a parse tree.
5. Ditto test 9.

**Comment by SophieStankus** [comment]
@justinnhli ready for review, although I wasn't sure if the bad variable name should be a syntax error or not but that's what I put

**Comment by SophieStankus** [comment]
@justinnhli added loop test cases but I can't figure out how to open a separate pull request for this so just adding a comment

**Comment by justinnhli** [comment]
1. Variables test 1 and 5 both have extra parenthesis around the declare value that should be deleted.
2. Variables test 10 is missing the s-expression.
3. Branch/Loop tests 1, 2, and 3's s-expressions all have a `declare` where it should be an `assign`. Note that this means the variable will need a `varloc` as well.
4. Branch/Loop test 3 also has a typo in the lang file - one of the braces is backwards.
5. Branch/Loop test 7 is an infinite loop. Based on your output, I assume you forgot to increment `x`.
6. Branch/Loop test 8 is missing the `==` node.
7. Branch/Loop test 10 is a syntax error - you cannot have an empty condition in an `if`.

Can you comment and tag me when you've fixed these two issues?

**Comment by SophieStankus** [comment]
@justinnhli revised

**Comment by justinnhli** [comment]
Fixed two tests for you. Test 7 for loop is still problematic, since we can't test infinite loops. Can you write another test case for that?

**Pull request merged**
