### PR TITLE
Control Flow Test Cases

### PR DESCRIPTION
**Pull request by dylane1999**

### CODE REVIEW

**Comment by justinnhli** [comment]
1. Test 1 has incorrect output.
2. Test 7 and 8 both have the wrong IR for if-else. It should be `ifelse` (one word), not `if_else`)
3. Test 10 should have the output of `syntax error`.

Comment and tag me when you're done!

**Comment by dylane1999** [comment]
Kind of Done, fixed the problems but my gitignore is causing conflicts @justinnhli

**Comment by justinnhli** [comment]
I'll deal with the gitignore thing. There's one remaining issue - test 5 is a syntax error (since I changed the syntax to disallow chained boolean comparisons, such as `10 > 2 == 1`. You can change it to `(10 > 2) == 1` to get the same effect.

**Comment by dylane1999** [comment]
fixed! @justinnhli

**Comment by justinnhli** [comment]
LGTM!

**Pull request merged**
