### PR TITLE
Add ten transform cases

### PR DESCRIPTION
**Pull request by kathyyliu**

### CODE REVIEW

**Comment by justinnhli** [comment]
Nice one. Your test 7 was the one that made me realize my code didn't match my algorithm :)

* 2.sexp has an error on the last print (should be a `+` instead of a `-`)
* 4.sexp should have `ifelse` instead of `elif`. 4.out is also missing.
* 5.out and 10.out are wrong (check wording on Moodle)
* 6.sexp2 has an extra `/` in the first line. 6.out is also wrong.
* 7.out has a spelling error ("`sequence`"). Both S-expressions are also incorrect (you have an extra `-` in the untransformed one)
* 8.sexp2 shouldn't have removed the `/ 1`

**Comment by kathyyliu** [comment]
@justinnhli

**Comment by justinnhli** [comment]
* 4.sexp and 4.sexp2 still should be `ifelse` :)
* 7.sexp2 remains wrong. My derivation:

    ```
    = 5 - (x + 2 - (3*1 - (0 - x - (1 - 2*x))))
    = 5 - (x + 2 - (3 - (0 - x - 1 + 2*x)))
    = 5 - (x + 2 - (3 - 0 + x + 1 - 2*x))
    = 5 - (x + 2 - 3 + 0 - x - 1 + 2*x)
    = 5 - x - 2 + 3 - 0 + x + 1 - 2*x
    = - x + x - 2*x + 5 - 2 + 3 - 0 + 1
    = - x + x - 2*x + 7
    = x - x - 2*x + 7
    ```

    Which should give the S-expression (ignoring lookups): `(+ (- (- x x) (* x 2)) 7)`

**Comment by kathyyliu** [comment]
@justinnhli Oops, you're right!

**Comment by justinnhli** [comment]
Still need `(lookup x)` instead of `x` for seven

**Comment by kathyyliu** [comment]
@justinnhli Sorry, I must've been rushing

**Comment by justinnhli** [comment]
np. merged!

**Pull request merged**
