### PR TITLE
Add class test cases

### PR DESCRIPTION
**Pull request by mhultgren**

### CODE REVIEW

**Comment by justinnhli** [comment]
Can't say as to the accuracy of your test cases, but you have a consistent error where your `member` and `memloc` S-expressions have the second argument wrapped in parenthesis (eg. `(member (lookup foo) (bar))` instead of `(member (lookup foo) bar)`. Fix that, tag me, and I'll take another look

**Comment by mhultgren** [comment]
Okay, updated .sexp files. I made some changes to the logic in my .toString() method for Parse, let me know if there are any bugs I didn't detect.

**Comment by mhultgren** [comment]
Just added transform test cases as well.

**Comment by justinnhli** [comment]
The classes test cases are fine, except for test4.sexp where you're missing a pair of parentheses around the `return`.

I'm not sure what your transform tests are doing - you're eliminating entire line and inlining functions?

**Comment by mhultgren** [comment]
Hm, I think I'm misunderstanding the function of dead code/store elimination & function inlining, I'm implementing typing & classes so writing the transform .sexp2 was a little guesswork. I'll go back and make some changes 👍

**Comment by justinnhli** [comment]
Ah - you're not misinterpreting it, but the test case should only cover constant folding, and only specific versions of that. Double check the slides and check Slack for what we do and don't transform, or just flag me down and ask!

**Comment by mhultgren** [comment]
Oh I see, I thought we were covering the 'other code transforms' but that makes sense. I'll go back, make changes, and let you know.

**Comment by justinnhli** [comment]
Dead code elimination is really cool, but also significant trickier to implement given our parser/interpreter. Maybe next time :)

**Comment by mhultgren** [comment]
Okay, just pushed new / edited test cases.

**Comment by justinnhli** [comment]
All the old tests look good! The new typechecking test 7 a few issues. The return type should just be `-> func`, not `-> ret func`. The S-expressions is missing the final `copy()`, and the output should have another `10`. Fix that and I'll merge them.

**Comment by mhultgren** [comment]
Okay, should be fixed now!

**Comment by justinnhli** [comment]
Looks like you have one more issue, still typechecking test 7 - your types are wrapped in individual parens when they shouldn't: `(signature (func) (int) (func))`

**Comment by mhultgren** [comment]
Oops!  Fixed, hopefully there aren't any more bugs.

**Comment by justinnhli** [comment]
Merged. Thanks!

**Pull request merged**
