### PR TITLE
Shuting_function_testcases

### PR DESCRIPTION
**Pull request by Shuting-sli2**
@justinnhli

### CODE REVIEW

**Comment by justinnhli** [comment]
* 2.out and 7.out both accidentally have code in it
* 6.out and 7.out should both be closures - you need to call the returned function(s) if you want the nested values.
* 2.sexp, 3.sexp, and 4.sexp has an extra `1` after the return
* 5.sexp has a bunch of issues - I recommend formatting the S-expression into something that follows the structure of your code, and making sure that you match each line.

**Comment by Shuting-sli2** [comment]
updated @justinnhli

**Comment by justinnhli** [comment]
Close - seven.out is wrong (I'm not sure what variable you expected to be already defined.)

**Comment by Shuting-sli2** [comment]
@justinnhli fixed seven.out

**Comment by justinnhli** [comment]
Merged. You had two files under 07-classes which I didn't include - when you do all the class testcases I'll merge those as well

**Pull request merged**
